version: "3.0"

services:
  nginx-php:
    container_name: local-alnp
    image: richarvey/nginx-php-fpm:1.10.3
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./conf/nginx/cert:/etc/nginx/cert
